#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PortkablePass.Android.Resource", IsApplication=true)]

namespace PortkablePass.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int charactersTextView = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int digitsCheckBox = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int domainEditText = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int domainTextView = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int generatedEditText = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int generatedTextView = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int hashTextView = 2131099657;
			
			// aapt resource value: 0x7f060016
			public const int lengthSeekBar = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int lengthTextView = 2131099668;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout2 = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout3 = 2131099658;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout4 = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int lowercaseCheckBox = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int masterEditText = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int masterTextView = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int radioGroup1 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int sha1RadioButton = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int sha256RadioButton = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int sha512RadioButton = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int specialCheckBox = 2131099667;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int uppercaseCheckBox = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
